version: '3.8'
services:
  gateway_server:
    image: "abahernest/adolla-store-gateway_server:1.1"
#    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "60061:60061"
    command: ["dist/main.js"]

